.INCLUDE /usr/pack/gf-45soi-kgf/arm/gf/45rfsoi/sc9_base_hvt/r0p0/cdl/sc9_soi12s0_base_hvt.cdl
.INCLUDE /usr/pack/gf-45soi-kgf/arm/gf/45rfsoi/sc9_base_svt/r0p0/cdl/sc9_soi12s0_base_svt.cdl
.INCLUDE /usr/pack/gf-45soi-kgf/arm/gf/45rfsoi/sc9_base_uvt/r0p0/cdl/sc9_soi12s0_base_uvt.cdl
.INCLUDE /usr/pack/gf-45soi-kgf/arm/gf/45rfsoi/io_gppr_t18_mv10_mv18_avt_pl/r0p0/cdl.dz/io_gppr_45rfsoi_t18_mv10_mv18_avt_pl.cdl
