`include /usr/pack/gf-45soi-kgf/arm/gf/45rfsoi/sc9_base_hvt/r0p0/verilog/sc9_soi12s0_base_hvt_neg.v
`include /usr/pack/gf-45soi-kgf/arm/gf/45rfsoi/sc9_base_svt/r0p0/verilog/sc9_soi12s0_base_svt_neg.v
`include /usr/pack/gf-45soi-kgf/arm/gf/45rfsoi/sc9_base_uvt/r0p0/verilog/sc9_soi12s0_base_uvt_neg.v
`include /usr/pack/gf-45soi-kgf/arm/gf/45rfsoi/io_gppr_t18_mv10_mv18_avt_pl/r0p0/verilog/io_gppr_soi12s0_t18_mv10_mv18_avt_pl.v
